version: '3'
services:
  sonsoftheforest:
    image: jammsen/sons-of-the-forest-dedicated-server:latest
    restart: always
    volumes:
      - sonsoftheforest:/sonsoftheforest
      - ./:/sonsoftheforest/userdata
      - steamcmd:/steamcmd
      - winedata:/winedata
    ports:
      - 8766:8766/udp
      - 27016:27016/udp
      - 9700:9700/udp
volumes:
  sonsoftheforest:
  steamcmd:
  winedata:
